---

- hosts: ubuntu
  become: yes
  
  tasks: 
   - name: install stuff
#     apt: name= {{ item }} update_cache=yes state=latest
     debug: msg={{ item }}
     with_items: 
     - vim 
     - nano
     - apache2
