---
- name: Get device information
  hosts: srx
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
#    - name: Get software and uptime information
#      juniper_junos_command:
#        commands: 
#          - "show version"
#          - "show system uptime"
#      register: junos_result
#
#    - name: Print response
#      debug:
#        var: junos_result.results

    - name: save output to dest
      juniper_junos_command:
        command: "show system uptime"
        dest: "/home/amrinder/AnsibleLearning/Juniper/logs/{{ inventory_hostname }}.uptime"
