---

- hosts: localhost
  vars:
   host: "desklab-fortigate"
   username: "admin"
   password: "Password!"
  tasks:
  - name: Static
    fortiosconfig:
     action: "set"
     host:  "{{  host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     config: "router static"
     https: false
     config_parameters:
      seq-num: "34"
      dst: "1.1.1.1 255.255.255.255"
      device: "wan1"
      gateway: "172.28.129.1"
