---

- hosts: ubuntu
  vars:
   - var_thing: "never_gonna"

  tasks: 
   - name: echo stuff
     command: echo -e "{{ var_thing }} give you up,\n{{ var_thing }}, \n{{ var_thing }} run around and dessert you" 
     register: results
   - name: show results
     #debug: msg={{ results.stdout_lines }}
     debug: msg={{ results }} 

